/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_scnu_libhttpserver_httpserver_UDPChat_sockInfo */

#ifndef _Included_cn_edu_scnu_libhttpserver_httpserver_UDPChat_sockInfo
#define _Included_cn_edu_scnu_libhttpserver_httpserver_UDPChat_sockInfo

#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
