/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_scnu_libhttpserver_httpserver_UDPChat */



#ifndef _Included_cn_edu_scnu_libhttpserver_httpserver_UDPChat
#define _Included_cn_edu_scnu_libhttpserver_httpserver_UDPChat

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_scnu_libhttpserver_httpserver_UDPChat
 * Method:    JoinInGroup
 * Signature: (Ljava/lang/String;ILcn/edu/scnu/libhttpserver/httpserver/UDPChat/sockInfo;)V
 */
JNIEXPORT void JNICALL Java_cn_edu_scnu_libhttpserver_httpserver_UDPChat_joinInGroup
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     cn_edu_scnu_libhttpserver_httpserver_UDPChat
 * Method:    SendMessage
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_edu_scnu_libhttpserver_httpserver_UDPChat_sendMessage
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     cn_edu_scnu_libhttpserver_httpserver_UDPChat
 * Method:    RecvMessage
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_cn_edu_scnu_libhttpserver_httpserver_UDPChat_recvMessage
  (JNIEnv *, jclass, jint,jstring);

/*
 * Class:     cn_edu_scnu_libhttpserver_httpserver_UDPChat
 * Method:    QuitGroup
 * Signature: (I[C)V
 */
JNIEXPORT void JNICALL Java_cn_edu_scnu_libhttpserver_httpserver_UDPChat_quitGroup
  (JNIEnv *, jclass, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
