/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_scnu_libhttpserver_httpserver_UDPChat */
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
// #include "ifaddrs.h"
#include <arpa/inet.h>
#include <netinet/in.h>
#include <unistd.h>
#include <netdb.h>
#include <string.h>
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <iostream>
using namespace std;



#define MSG_SIZE 6400

#define MCAST_ADDR "224.1.1.85"
typedef struct sockInfo{
    int sender_fd;
    int recver_fd;
    int port;
}sockInfo;


#ifndef _Included_cn_edu_scnu_libhttpserver_httpserver_UDPChat
#define _Included_cn_edu_scnu_libhttpserver_httpserver_UDPChat

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_scnu_libhttpserver_httpserver_UDPChat
 * Method:    JoinInGroup
 * Signature: (Ljava/lang/String;ILcn/edu/scnu/libhttpserver/httpserver/UDPChat/sockInfo;)V
 */
JNIEXPORT jobject JNICALL Java_cn_edu_scnu_libhttpserver_httpserver_UDPChat_joinInGroup
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     cn_edu_scnu_libhttpserver_httpserver_UDPChat
 * Method:    SendMessage
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_edu_scnu_libhttpserver_httpserver_UDPChat_sendMessage
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     cn_edu_scnu_libhttpserver_httpserver_UDPChat
 * Method:    RecvMessage
 * Signature: (I[C)I
 */
JNIEXPORT jstring JNICALL Java_cn_edu_scnu_libhttpserver_httpserver_UDPChat_recvMessage
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_edu_scnu_libhttpserver_httpserver_UDPChat
 * Method:    QuitGroup
 * Signature: (I[C)V
 */
JNIEXPORT void JNICALL Java_cn_edu_scnu_libhttpserver_httpserver_UDPChat_quitGroup
  (JNIEnv *, jclass, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
