# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/CMakeCInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/CMakeCXXInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/CMakeCommonLanguageInclude.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/CMakeLanguageInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Compiler/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Compiler/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Compiler/CMakeCommonCompilerMacros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Compiler/GNU.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Platform/Darwin-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Platform/Darwin-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Platform/Darwin-Clang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Platform/Darwin-Clang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Platform/Darwin-Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.10/Modules/Platform/UnixPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mahuijie/Desktop/ChatLib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mahuijie/Desktop/ChatLib/ios_arm64_build/CMakeFiles/3.10.0-rc4/CMakeCCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mahuijie/Desktop/ChatLib/ios_arm64_build/CMakeFiles/3.10.0-rc4/CMakeCXXCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mahuijie/Desktop/ChatLib/ios_arm64_build/CMakeFiles/3.10.0-rc4/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mahuijie/Desktop/ChatLib/lib/CMakeLists.txt))

/Users/mahuijie/Desktop/ChatLib/ios_arm64_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/mahuijie/Desktop/ChatLib -B/Users/mahuijie/Desktop/ChatLib/ios_arm64_build
